package br.unicamp.Game;

public enum Command {

	MOVE, END_TURN, OPEN_DOOR,OPEN_CHEST, SEARCH_TRAP, BAG_REPORT,ATTACK, DRINK_POTION, CHANGE_ARMOR, CHANGE_WEAPON, QUIT, NONE,PREGAME,FROM_TXT, PLAYER_STATUS, HELP, MAGIC

}
