package br.unicamp.Game;

public enum Command {
	MOVE, UP, DOWN, LEFT, RIGHT, OPEN_DOOR,OPEN_CHEST, BAG_REPORT,ATTACK, DRINK_POTION, CHANGE_ARMOR, CHANGE_WEAPON, QUIT, NONE,PREGAME,FROM_TXT, PLAYER_STATUS, HELP

}
